import { QRGenerator } from '@/components/qr/QRGenerator';
import { URLForm } from '@/components/qr/forms/URLForm';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Link QR Code Generator - Free & Easy | QR Studio',
  description: 'Create a QR code for any website URL instantly. Free, no signup required, and high-quality downloads in PNG and SVG formats.',
};

const faqItems = [
  {
    question: 'Do these QR codes expire?',
    answer: 'No, the QR codes generated by our tool are static and will never expire. They will work indefinitely as long as the URL you encoded remains active. This makes them perfect for printed materials like business cards or marketing flyers.',
  },
  {
    question: 'Can I edit the URL after creating the QR code?',
    answer: 'Since these are static QR codes, the URL is encoded directly into the pattern. This means you cannot change the destination URL once the code is generated. If you need to change the link, you will need to create a new QR code.',
  },
  {
    question: 'What is the maximum URL length?',
    answer: 'While QR codes can technically hold very long URLs, we recommend keeping them under 200 characters for the best scanning reliability. Longer URLs result in a denser, more complex QR code pattern that might be harder for some older phone cameras to read.',
  },
  {
    question: 'Can I use these QR codes for commercial purposes?',
    answer: 'Yes, you are free to use these QR codes for menus, marketing materials, business cards, or any other commercial use. Our tool is 100% free and we do not add any watermarks to your generated codes.',
  },
];

export default function URLQRPage() {
  return (
    <QRGenerator
      title="URL QR Code Generator"
      description="Convert any website link or URL into a scannable QR code. Perfect for menus, business cards, and marketing materials."
      type="url"
      formComponent={URLForm}
      faqItems={faqItems}
    />
  );
}
