import { QRGenerator } from '@/components/qr/QRGenerator';
import { URLForm } from '@/components/qr/forms/URLForm';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Link QR Code Generator - Free & Easy | QR Studio',
  description: 'Create a QR code for any website URL instantly. Free, no signup required, and high-quality downloads in PNG and SVG formats.',
};

const faqItems = [
  {
    question: 'Do these QR codes expire?',
    answer: 'No, the QR codes generated by our tool are static and will never expire. They will work as long as the URL you encoded remains active.',
  },
  {
    question: 'Is there a limit on how many QR codes I can create?',
    answer: 'Absolutely not! You can create as many QR codes as you need for free. There are no daily limits or subscriptions.',
  },
  {
    question: 'Can I use these QR codes for commercial purposes?',
    answer: 'Yes, you are free to use these QR codes for menus, marketing materials, business cards, or any other commercial use without attribution.',
  },
];

export default function URLQRPage() {
  return (
    <QRGenerator
      title="URL QR Code Generator"
      description="Convert any website link or URL into a scannable QR code. Perfect for menus, business cards, and marketing materials."
      formComponent={URLForm}
      faqItems={faqItems}
    />
  );
}
