export interface FAQItem {
  id: string;
  question: string;
  answer: string;
}

export interface FAQCategory {
  name: string;
  questions: FAQItem[];
}

export const generalFAQ: FAQCategory[] = [
  {
    name: 'Getting Started',
    questions: [
      {
        id: 'how-to-create',
        question: 'How do I create a QR code?',
        answer: 'Creating a QR code is simple and takes less than 30 seconds. First, choose the type of QR code you want to create (URL, WiFi, Email, etc.). Next, enter your information in the input fields provided. Once you\'re ready, click "Generate QR Code" to see your custom code. Finally, download your QR code as a high-quality PNG for digital use or a scalable SVG for printing. Our tool generates QR codes instantly in your browser, so there\'s no signup required and your data stays private.'
      },
      {
        id: 'how-to-download',
        question: 'How do I download a QR code?',
        answer: 'After generating your QR code, you will see download options next to the preview image. We provide two main formats: PNG and SVG. Simply click the button for your preferred format, and the file will be saved directly to your device. PNG is best for social media and websites, while SVG is ideal for high-quality printing as it can be scaled to any size without losing clarity.'
      },
      {
        id: 'png-vs-svg',
        question: 'What\'s the difference between PNG and SVG?',
        answer: 'PNG (Portable Network Graphics) is a raster image format, meaning it\'s made of pixels. It\'s perfect for digital use, such as on websites, social media, or in emails. SVG (Scalable Vector Graphics), on the other hand, is a vector format. This means it\'s made of mathematical paths and can be scaled to any size—from a business card to a billboard—without ever becoming pixelated or blurry. We recommend SVG for any professional printing needs.'
      },
      {
        id: 'mobile-creation',
        question: 'Can I create QR codes on mobile?',
        answer: 'Yes, our QR code generator is fully responsive and works perfectly on all mobile devices, including iPhones, iPads, and Android smartphones. You can generate, customize, and download your QR codes directly from your mobile browser without needing to install any additional apps. This makes it easy to create codes on the go for events or quick sharing.'
      },
      {
        id: 'how-to-scan',
        question: 'How do I scan a QR code?',
        answer: 'Most modern smartphones have a QR code scanner built directly into the default camera app. Simply open your camera, point it at the QR code, and wait for a notification or link to appear on your screen. Tap the notification to open the content. If your phone is older and doesn\'t support this, you can download a free QR code scanner app from the Apple App Store or Google Play Store.'
      },
      {
        id: 'qr-size',
        question: 'What size should my QR code be?',
        answer: 'The ideal size for a QR code depends on the scanning distance. For small items like business cards, a minimum size of 2 x 2 cm (0.8 x 0.8 inches) is recommended. For larger items like posters or flyers, the code should be larger to ensure it can be scanned from a distance. A good rule of thumb is a 10:1 ratio (e.g., if the scanner is 1 meter away, the QR code should be at least 10 cm wide).'
      }
    ]
  },
  {
    name: 'Technical Questions',
    questions: [
      {
        id: 'do-qr-expire',
        question: 'Do QR codes expire?',
        answer: 'No, the QR codes generated by our tool never expire. We create "static" QR codes, which means the information is encoded directly into the pattern itself. As long as the information you encoded (like a website URL) remains active, the QR code will continue to work indefinitely. This makes them a reliable choice for long-term use on printed materials like business cards or product packaging.'
      },
      {
        id: 'error-correction',
        question: 'What is error correction in QR codes?',
        answer: 'Error correction is a built-in feature of QR codes that allows them to remain scannable even if they are partially damaged, dirty, or obscured. It works by adding redundant data to the code. There are four levels of error correction (L, M, Q, H), with "H" offering the highest level of protection (up to 30% damage). Our tool uses an optimized level to balance scan reliability with a clean, professional appearance.'
      },
      {
        id: 'data-capacity',
        question: 'How much data can a QR code hold?',
        answer: 'A standard QR code can hold a significant amount of data, including up to 4,296 alphanumeric characters or 7,089 numeric characters. However, as you add more data, the QR code pattern becomes denser and more complex, which can make it harder for some cameras to scan quickly. For the best user experience, we recommend keeping your content concise, especially for URLs.'
      },
      {
        id: 'offline-work',
        question: 'Do QR codes work offline?',
        answer: 'Yes, certain types of QR codes work entirely offline. For example, Text, WiFi, and vCard QR codes contain all the necessary information within the code itself. When scanned, the phone can display the text or connect to the WiFi without needing an active internet connection. However, URL QR codes require an internet connection to load the website they point to once the scan is complete.'
      },
      {
        id: 'universal-standard',
        question: 'Are QR codes universal?',
        answer: 'Yes, QR codes are a global standard (ISO/IEC 18004) and can be scanned by any standard QR reader anywhere in the world. Whether you are in New York, Tokyo, or London, a QR code generated here will work the same way. This universal compatibility makes them one of the most effective tools for international marketing and information sharing.'
      }
    ]
  },
  {
    name: 'Privacy & Security',
    questions: [
      {
        id: 'is-it-free',
        question: 'Is this QR generator really free?',
        answer: 'Yes, our QR code generator is 100% free to use. There are no hidden fees, no subscriptions, and no limits on how many codes you can create. We don\'t add watermarks to your codes, and you are free to use them for both personal and commercial projects. We believe in providing a high-quality, accessible tool for everyone.'
      },
      {
        id: 'data-storage',
        question: 'Do you store my QR code data?',
        answer: 'No, we do not store the data you enter to generate your QR codes. Our tool is designed to process everything locally in your browser. When you click "Generate," the code is created on your device, and the data is never sent to our servers. This ensures your information, such as WiFi passwords or private messages, remains completely private and secure.'
      },
      {
        id: 'qr-viruses',
        question: 'Can QR codes contain viruses?',
        answer: 'A QR code itself is just a piece of data and cannot contain a virus. However, like any link, a QR code can point to a malicious website. It is important to only scan QR codes from trusted sources. Our tool only generates the codes you request and does not add any hidden links or redirects, ensuring that the codes you create are as safe as the information you provide.'
      },
      {
        id: 'signup-required',
        question: 'Do I need to sign up to use this tool?',
        answer: 'No signup or registration is required to use our QR code generator. We want to make the process as fast and frictionless as possible. You can simply visit our site, enter your information, and download your QR code instantly. We don\'t ask for your email address or any personal information, allowing you to maintain your privacy while using our services.'
      }
    ]
  },
  {
    name: 'Business Use',
    questions: [
      {
        id: 'commercial-use',
        question: 'Can I use QR codes for my business?',
        answer: 'Absolutely! QR codes are an incredibly versatile tool for businesses of all sizes. You can use them on business cards to share contact info, on restaurant menus for contactless ordering, on product packaging for manuals, or on marketing posters to drive traffic to your website. Because our codes are free and high-resolution, they are perfect for professional use in any industry.'
      },
      {
        id: 'marketing-benefits',
        question: 'Are QR codes good for marketing?',
        answer: 'Yes, QR codes are a powerful bridge between physical and digital marketing. They allow you to track engagement from offline materials like flyers and billboards by using UTM parameters in your URLs. They provide a "frictionless" way for customers to interact with your brand—instead of typing a long URL, they can simply scan and arrive at your landing page in seconds.'
      },
      {
        id: 'business-cards',
        question: 'Can I use QR codes on business cards?',
        answer: 'Yes, using a QR code on a business card is a modern and efficient way to share your contact details. You can create a URL QR code that points to your LinkedIn profile or portfolio, or a vCard QR code that allows people to save your contact information directly to their phone\'s address book with a single scan. It saves space on your card and makes it easier for people to reach you.'
      }
    ]
  },
  {
    name: 'Troubleshooting',
    questions: [
      {
        id: 'wont-scan',
        question: 'Why won\'t my QR code scan?',
        answer: 'There are a few common reasons why a QR code might not scan. First, check the contrast; a dark code on a light background is easiest to read. Second, ensure the code isn\'t too small for the scanning distance. Third, check for blurriness or low resolution—using our SVG format for printing prevents this. Finally, make sure there is enough empty space (the "quiet zone") around the code so the scanner can identify it.'
      },
      {
        id: 'blurry-qr',
        question: 'My QR code is blurry, what should I do?',
        answer: 'If your QR code looks blurry, it\'s likely because you are using a low-resolution raster image (like a small PNG) and trying to scale it up. To fix this, always download the SVG version of your QR code for printing or large-scale use. SVG files are vector-based and will remain perfectly sharp at any size. If you are using it for a website, ensure you download a PNG at a size that matches or exceeds its display dimensions.'
      },
      {
        id: 'download-issue',
        question: 'Why is the download button not working?',
        answer: 'If the download button isn\'t responding, try refreshing the page and generating the code again. Ensure that you have a stable internet connection and that your browser is up to date. Occasionally, browser extensions or ad-blockers can interfere with the download process; try disabling them temporarily or using an incognito/private window to see if that resolves the issue.'
      }
    ]
  }
];
