import { EmailIcon, PhoneIcon, TextIcon, UrlIcon, WifiIcon } from '@/components/ui/Icons';
import { ReactNode } from 'react';

export interface FAQItem {
  question: string;
  answer: string;
}

export interface UseCase {
  title: string;
  description: string;
}

export interface QRTool {
  id: string;
  name: string;
  path: string;
  description: string;
  longDescription: string;
  icon: ReactNode;
  color: string;
  metaTitle: string;
  metaDescription: string;
  faqItems: FAQItem[];
  bestPractices: string[];
  useCases: UseCase[];
}

export const tools: QRTool[] = [
  {
    id: 'url',
    name: 'URL QR Code',
    path: '/url',
    description: 'Convert any website link into a scannable QR code.',
    longDescription: 'Our URL QR Code generator is a powerful tool for bridging the gap between physical and digital worlds. By converting any website link or URL into a scannable QR code, you enable users to access your content instantly without the friction of manual typing. This technology is essential for modern marketing, allowing you to track offline conversions, simplify menu access in restaurants, and enhance professional networking on business cards. We generate high-resolution, static QR codes that follow international standards (ISO/IEC 18004), ensuring compatibility across all scanning devices and operating systems.',
    icon: <UrlIcon className="w-8 h-8" />,
    color: 'bg-indigo-50 text-indigo-600',
    metaTitle: 'Professional URL QR Code Generator - Free & Privacy-Focused | QR Studio',
    metaDescription: 'Create high-resolution URL QR codes for free. No registration required. Perfect for marketing, menus, and business cards with local browser-based generation.',
    faqItems: [
      {
        question: 'Do these QR codes ever expire?',
        answer: 'No, the QR codes generated by QR Studio are "static," meaning the URL is encoded directly into the pattern. They will never expire and will work indefinitely as long as your destination website remains active. Unlike "dynamic" QR codes, they do not rely on a central server to redirect users.',
      },
      {
        question: 'Can I track how many people scan my QR code?',
        answer: 'Since we provide static QR codes for privacy and permanence, we do not track scans on our end. However, you can easily track performance by using UTM parameters (e.g., ?utm_source=qr_code) in the URL you encode. This allows you to see the traffic in your own Google Analytics or other web analytics tools.',
      },
      {
        question: 'What is the maximum character limit for a URL?',
        answer: 'While QR codes can technically hold up to 4,296 characters, we strongly recommend keeping URLs under 200 characters. Longer URLs create a denser, more complex pattern that requires a higher-quality camera and better lighting to scan successfully.',
      },
      {
        question: 'How do I ensure my QR code scans every time?',
        answer: 'Ensure high contrast between the code (dark) and the background (light). Also, maintain a "quiet zone"—a clear border around the code—to help scanners identify it. For printed materials, always test the code at the intended size before final production.',
      },
      {
        question: 'Can I use these for commercial advertising?',
        answer: 'Absolutely. All QR codes generated here are 100% free for both personal and commercial use. We do not add watermarks or redirect screens, ensuring a professional experience for your customers.',
      },
      {
        question: 'What format should I use for printing?',
        answer: 'We recommend downloading the SVG (Scalable Vector Graphics) format for any printed materials. SVGs are vector-based, meaning they can be scaled to any size—from a postage stamp to a billboard—without losing any quality or becoming pixelated.',
      },
    ],
    bestPractices: [
      'Use high contrast: Dark code on a light background works best.',
      'Maintain a "Quiet Zone": Keep a clear margin around the QR code.',
      'Test before printing: Always scan the code with multiple devices.',
      'Keep it simple: Use URL shorteners for very long web addresses.',
      'Consider the size: Ensure the code is at least 2cm x 2cm for close scanning.',
    ],
    useCases: [
      { title: 'Restaurant Menus', description: 'Replace physical menus with a scan-to-order system, reducing printing costs and improving hygiene.' },
      { title: 'Real Estate Signage', description: 'Place QR codes on "For Sale" signs to link directly to virtual tours, high-res photos, and property details.' },
      { title: 'Personal Portfolios', description: 'Add a QR code to your resume or business card that links to your LinkedIn profile or online portfolio.' },
      { title: 'Event RSVP', description: 'Include a QR code on wedding or conference invitations for instant digital registration and RSVP tracking.' }
    ],
  },
  {
    id: 'wifi',
    name: 'WiFi QR Code',
    path: '/wifi',
    description: 'Share your WiFi network details without typing passwords.',
    longDescription: 'The WiFi QR Code generator is a game-changer for hospitality and home networking. Instead of reading out complex passwords or printing them on vulnerable pieces of paper, you can provide a secure, scannable code. This tool creates a specialized QR code that uses the standard WiFi protocol supported by Android and iOS. When scanned, the device automatically recognizes the network name (SSID), security type (WPA/WPA2/WEP), and password, prompting the user to join with a single tap. This is ideal for cafes, Airbnb hosts, and office guest networks where speed and security are top priorities.',
    icon: <WifiIcon className="w-8 h-8" />,
    color: 'bg-emerald-50 text-emerald-600',
    metaTitle: 'Secure WiFi QR Code Generator - Share Passwords Safely | QR Studio',
    metaDescription: 'Generate secure WiFi QR codes to share your network instantly. Guests scan to connect without typing. Local generation ensures your password stays private.',
    faqItems: [
      {
        question: 'Is my WiFi password safe when using this generator?',
        answer: 'Yes, your security is our priority. QR Studio generates the QR code entirely within your browser using client-side JavaScript. Your WiFi password and SSID are never sent to our servers and never stored. The data stays on your machine.',
      },
      {
        question: 'Does this work for both iPhone and Android?',
        answer: 'Yes. Most modern smartphones have native support for WiFi QR codes. This includes iPhones running iOS 11+ and Android devices running Android 10+. Users simply point their camera, and the system handles the rest.',
      },
      {
        question: 'What if my WiFi network is hidden?',
        answer: 'Our generator includes a "Hidden" network option. If your SSID is not broadcast, check this box. It adds a specific flag to the QR code that tells the scanning device to search for the network even if it\'s not visible in a standard scan.',
      },
      {
        question: 'Which security type should I choose?',
        answer: 'Most modern routers use WPA/WPA2 (often labeled as WPA/WPA2-PSK). This is the current standard for home and small business security. WEP is an older, less secure protocol and is rarely used today.',
      },
      {
        question: 'Can I change the password later?',
        answer: 'Because these are static QR codes, the password is baked into the image. If you change your WiFi password, you must generate and print a new QR code for your guests.',
      },
    ],
    bestPractices: [
      'Double-check your SSID: It must exactly match your router settings (including case).',
      'Choose the right security: WPA/WPA2 is standard for most modern networks.',
      'Place it visibly: In a cafe, place the code on every table or near the counter.',
      'Keep it private: Only share the QR code in areas intended for your guests.',
    ],
    useCases: [
      { title: 'Airbnb Guest Kits', description: 'Provide a professional welcome card with a WiFi QR code to help guests connect without typing complex keys.' },
      { title: 'Cafe & Restaurant Tables', description: 'Reduce staff interruptions by placing secure WiFi codes directly on tables or menu boards.' },
      { title: 'Coworking Spaces', description: 'Streamline onboarding for new members with instant access to the guest or member network.' },
      { title: 'Home Guest Access', description: 'A sleek, framed QR code in your living room allows friends to join your network securely.' }
    ],
  },
  {
    id: 'text',
    name: 'Text QR Code',
    path: '/text',
    description: 'Create a QR code for plain text messages and notes.',
    longDescription: 'The Text QR Code generator is a versatile utility for sharing information that doesn\'t require an internet connection. It encodes plain text directly into the QR code pattern. When scanned, any standard QR reader will immediately display the encoded text on the screen. This is incredibly useful for product SKU information, inventory management, secret messages, educational scavenger hunts, or providing offline instructions. Since the data is stored within the code itself, it works in remote locations, deep inside buildings, or anywhere with poor cellular reception.',
    icon: <TextIcon className="w-8 h-8" />,
    color: 'bg-violet-50 text-violet-600',
    metaTitle: 'Plain Text QR Code Generator - Offline Information Sharing | QR Studio',
    metaDescription: 'Convert text, notes, and messages into QR codes. Works offline without an internet connection. Secure and private local generation.',
    faqItems: [
      {
        question: 'How much text can I realistically fit?',
        answer: 'While the theoretical limit is over 4,000 characters, scan reliability drops significantly after 500 characters. For the best experience across all phone types, we recommend keeping your text concise and well-formatted.',
      },
      {
        question: 'Do I need internet to scan a text QR code?',
        answer: 'No. This is one of the main advantages of text QR codes. Since the message is stored in the data pixels of the image, the scanning device can decode and display it without any network access.',
      },
      {
        question: 'Can I include emojis and special characters?',
        answer: 'Yes. Our generator uses UTF-8 encoding, which supports a wide range of symbols, international characters, and modern emojis. We recommend testing to ensure the scanning app displays them correctly.',
      },
      {
        question: 'Is this a good way to share sensitive notes?',
        answer: 'While the generation is private (done on your local machine), anyone who scans the code can see the text. Do not use QR codes for highly sensitive data like clear-text banking passwords in public places.',
      },
    ],
    bestPractices: [
      'Be concise: Shorter text results in a cleaner, more reliable QR code.',
      'Use paragraphs: For longer notes, use line breaks to make the text readable on the phone.',
      'Verify formatting: Some scanners may strip leading/trailing whitespace.',
    ],
    useCases: [
      { title: 'Inventory Management', description: 'Label warehouse items with QR codes containing SKU numbers, batch dates, and storage instructions.' },
      { title: 'Educational Scavenger Hunts', description: 'Create interactive learning experiences by hiding offline text clues around a campus or museum.' },
      { title: 'Product SKUs', description: 'Include technical specs or serialization data on product packaging that works without an internet connection.' },
      { title: 'Secret Messaging', description: 'A fun way to share surprise notes or gift clues that can only be read with a quick scan.' }
    ],
  },
  {
    id: 'email',
    name: 'Email QR Code',
    path: '/email',
    description: 'Pre-fill email recipient and subject for quick contact.',
    longDescription: 'The Email QR Code generator simplifies lead generation and customer support. By encoding the "mailto:" protocol, it allows users to start an email conversation with exactly one scan. You can pre-set the recipient email address, a descriptive subject line, and even a starting body message. This removes the barrier of users having to manually type your email address, which is prone to errors. It\'s a perfect addition to "Contact Us" pages, product packaging for support requests, or RSVP cards for events.',
    icon: <EmailIcon className="w-8 h-8" />,
    color: 'bg-fuchsia-50 text-fuchsia-600',
    metaTitle: 'Email QR Code Generator - Streamline Customer Contact | QR Studio',
    metaDescription: 'Create email QR codes with pre-filled subjects and messages. Make it easy for customers to reach you with a single scan.',
    faqItems: [
      {
        question: 'How does the email QR code work?',
        answer: 'It uses the "mailto:" URI scheme. When a smartphone scans the code, it triggers a command to open the user\'s default email client (like Mail, Gmail, or Outlook) and populates the fields you defined.',
      },
      {
        question: 'Will it work with Gmail or Outlook?',
        answer: 'Yes. Because it uses a standard protocol, it will trigger whatever app the user has set as their "default" for emails on their operating system.',
      },
      {
        question: 'Can I add multiple recipients?',
        answer: 'The standard protocol allows for multiple recipients separated by commas, but we recommend sticking to one primary address to ensure the best compatibility across all mobile email apps.',
      },
      {
        question: 'Can I include attachments?',
        answer: 'No, the "mailto:" protocol does not support pre-filling attachments for security reasons. You should instead include a link to the file in the body of the email.',
      },
    ],
    bestPractices: [
      'Use a clear subject line: This helps you filter incoming emails from QR scans.',
      'Keep the body short: Some email clients have limits on the length of pre-filled text.',
      'Always test: Different email apps handle line breaks and special characters differently.',
    ],
    useCases: [
      { title: 'Customer Support', description: 'Print codes on packaging that pre-fill your support email and the specific product model number.' },
      { title: 'RSVP for Invitations', description: 'Streamline event planning by pre-filling the subject line with "RSVP: [Event Name]" for guest responses.' },
      { title: 'Sales Inquiries', description: 'Place QR codes on brochures to capture leads with pre-written subject lines like "Inquiry about [Service Name]."' },
      { title: 'Feedback Forms', description: 'Gather direct feedback from store visitors by simplifying the email creation process.' }
    ],
  },
  {
    id: 'phone',
    name: 'Phone QR Code',
    path: '/phone',
    description: 'Generate a QR code that opens the dialer with your number.',
    longDescription: 'The Phone QR Code generator is the fastest way for customers to reach your sales or support line. In an era where "click-to-call" is king on the web, "scan-to-call" takes over in the physical world. This tool creates a "tel:" link that, when scanned, opens the phone\'s native dialer app with your number already entered. This is exceptionally effective on posters, billboards, and business cards, reducing the effort required for a customer to make a call to almost zero.',
    icon: <PhoneIcon className="w-8 h-8" />,
    color: 'bg-sky-50 text-sky-600',
    metaTitle: 'Phone Number QR Code Generator - Scan to Call | QR Studio',
    metaDescription: 'Generate "Scan to Call" QR codes. Perfect for business cards and support lines. Fast, free, and privacy-focused generation.',
    faqItems: [
      {
        question: 'Will the phone call start immediately?',
        answer: 'No. For security and user control, the scan will open the dialer with the number pre-filled, but the user must still press the "Call" button to initiate the conversation.',
      },
      {
        question: 'Should I include the country code?',
        answer: 'Yes, absolutely. To ensure your QR code works for international travelers or users with different regional settings, always use the full international format (e.g., +1 for USA, +44 for UK).',
      },
      {
        question: 'Does this work for SMS?',
        answer: 'This specific tool is for phone calls. If you want to pre-fill a text message, you should use our specialized SMS QR code generator (coming soon) or a custom URL using the "sms:" protocol.',
      },
      {
        question: 'Can I use an extension number?',
        answer: 'Support for extensions in QR codes is limited and inconsistent across devices. It is best to use a direct line for the most reliable user experience.',
      },
    ],
    bestPractices: [
      'Use international format: Start with "+" followed by the country code.',
      'Provide a backup: Always print the actual phone number next to the QR code for accessibility.',
      'Time your campaign: Ensure your phone lines are staffed when users are likely to scan.',
    ],
    useCases: [
      { title: 'Real Estate Agents', description: 'Make it effortless for potential buyers to call for a viewing directly from your "For Sale" yard sign.' },
      { title: 'Urgent Support Lines', description: 'Provide a "Scan to Call" option on industrial machinery or critical infrastructure for immediate assistance.' },
      { title: 'Direct Sales Calls', description: 'Enhance your business cards with a phone QR code to turn networking into immediate voice conversions.' },
      { title: 'Service Appointments', description: 'Place QR codes on service stickers (e.g., HVAC, plumbing) to make re-booking or emergency calls instant.' }
    ],
  },
];
