import { EmailIcon, PhoneIcon, TextIcon, UrlIcon, WifiIcon } from '@/components/ui/Icons';
import { ReactNode } from 'react';

export interface FAQItem {
  question: string;
  answer: string;
}

export interface QRTool {
  id: string;
  name: string;
  path: string;
  description: string;
  longDescription: string;
  icon: ReactNode;
  color: string;
  metaTitle: string;
  metaDescription: string;
  faqItems: FAQItem[];
}

export const tools: QRTool[] = [
  {
    id: 'url',
    name: 'URL QR Code',
    path: '/url',
    description: 'Convert any website link into a scannable QR code.',
    longDescription: 'Convert any website link or URL into a scannable QR code. Perfect for menus, business cards, and marketing materials.',
    icon: <UrlIcon className="w-8 h-8" />,
    color: 'bg-indigo-50 text-indigo-600',
    metaTitle: 'Link QR Code Generator - Free & Easy | QR Studio',
    metaDescription: 'Create a QR code for any website URL instantly. Free, no signup required, and high-quality downloads in PNG and SVG formats.',
    faqItems: [
      {
        question: 'Do these QR codes expire?',
        answer: 'No, the QR codes generated by our tool are static and will never expire. They will work indefinitely as long as the URL you encoded remains active. This makes them perfect for printed materials like business cards or marketing flyers.',
      },
      {
        question: 'Can I edit the URL after creating the QR code?',
        answer: 'Since these are static QR codes, the URL is encoded directly into the pattern. This means you cannot change the destination URL once the code is generated. If you need to change the link, you will need to create a new QR code.',
      },
      {
        question: 'What is the maximum URL length?',
        answer: 'While QR codes can technically hold very long URLs, we recommend keeping them under 200 characters for the best scanning reliability. Longer URLs result in a denser, more complex QR code pattern that might be harder for some older phone cameras to read.',
      },
      {
        question: 'Can I use these QR codes for commercial purposes?',
        answer: 'Yes, you are free to use these QR codes for menus, marketing materials, business cards, or any other commercial use. Our tool is 100% free and we do not add any watermarks to your generated codes.',
      },
    ],
  },
  {
    id: 'wifi',
    name: 'WiFi QR Code',
    path: '/wifi',
    description: 'Share your WiFi network details without typing passwords.',
    longDescription: 'Let guests join your WiFi network instantly by scanning a QR code. Ideal for cafes, restaurants, and home guest rooms.',
    icon: <WifiIcon className="w-8 h-8" />,
    color: 'bg-emerald-50 text-emerald-600',
    metaTitle: 'WiFi QR Code Generator - Share Your WiFi Easily | QR Studio',
    metaDescription: 'Create a WiFi QR code to share your network details. Guests can scan to join your WiFi instantly without typing passwords.',
    faqItems: [
      {
        question: 'How do I create a WiFi QR code?',
        answer: 'Creating a WiFi QR code is simple. Enter your network name (SSID), password, and select the security type (WPA/WPA2 is most common). Click "Generate QR Code" and download it. When someone scans this code, they\'ll automatically connect to your network without typing the password.',
      },
      {
        question: 'Do WiFi QR codes work on all phones?',
        answer: 'Yes, WiFi QR codes work on most modern smartphones. iOS devices (iPhone) running iOS 11 or later and Android devices running Android 10 or later can scan and connect directly through their camera app.',
      },
      {
        question: 'Is it safe to share my WiFi via QR code?',
        answer: 'WiFi QR codes are generally safe for trusted environments like your home or office. Our tool generates the QR code locally in your browser, so your WiFi password is never sent to our servers or stored anywhere.',
      },
      {
        question: 'Can I create a QR code for hidden WiFi networks?',
        answer: 'Yes, but ensure you check the "Hidden" option if your network SSID is not broadcast. This tells the scanning device to look for the network even if it\'s not visible in the standard scan list.',
      },
    ],
  },
  {
    id: 'text',
    name: 'Text QR Code',
    path: '/text',
    description: 'Create a QR code for plain text messages and notes.',
    longDescription: 'Create a QR code for plain text. Perfect for short notes, product information, or simple messages that need to be read offline.',
    icon: <TextIcon className="w-8 h-8" />,
    color: 'bg-violet-50 text-violet-600',
    metaTitle: 'Text QR Code Generator - Convert Text to QR | QR Studio',
    metaDescription: 'Convert any plain text into a QR code. Useful for secret messages, notes, and information sharing without an internet connection.',
    faqItems: [
      {
        question: 'How much text can I put in a QR code?',
        answer: 'While QR codes can technically hold up to 4,000 characters, we recommend keeping your text under 500 characters for the best scanning reliability. Longer text makes the QR code pattern denser and harder for some phone cameras to read.',
      },
      {
        question: 'Does scanning a text QR code require internet?',
        answer: 'No. The text is encoded directly into the QR code pattern. When scanned, the text will be displayed on the phone even if there is no internet connection, making it perfect for offline information sharing.',
      },
      {
        question: 'Can I include special characters and emojis?',
        answer: 'Yes, our text QR code generator supports UTF-8 encoding, which means you can include special characters, symbols, and even emojis in your messages.',
      },
      {
        question: 'Is my text data private?',
        answer: 'Absolutely. Our tool generates the QR code entirely in your browser. Your text is never sent to our servers or stored anywhere, ensuring 100% privacy for your messages.',
      },
    ],
  },
  {
    id: 'email',
    name: 'Email QR Code',
    path: '/email',
    description: 'Pre-fill email recipient and subject for quick contact.',
    longDescription: 'Make it easy for people to email you. One scan opens their email app with your address and a subject line already filled in.',
    icon: <EmailIcon className="w-8 h-8" />,
    color: 'bg-fuchsia-50 text-fuchsia-600',
    metaTitle: 'Email QR Code Generator - Quick Email Contact | QR Studio',
    metaDescription: 'Create an email QR code with a pre-filled address and subject. Scanning the code opens the user\'s email app automatically.',
    faqItems: [
      {
        question: 'How do I create an email QR code?',
        answer: 'Enter the recipient\'s email address, a subject line, and an optional message body. Click "Generate" and download your QR code. When scanned, it will automatically open the user\'s default email app with all the fields pre-filled.',
      },
      {
        question: 'Can I pre-fill the email subject and body?',
        answer: 'Yes! Our tool allows you to include a subject and a message body. This is perfect for RSVPing to events, requesting support, or starting a specific conversation with your customers.',
      },
      {
        question: 'Do email QR codes work on all devices?',
        answer: 'Yes, email QR codes use the standard "mailto:" protocol, which is supported by virtually all modern smartphones and email clients, including Gmail, Outlook, and Apple Mail.',
      },
      {
        question: 'Can I send attachments through email QR codes?',
        answer: 'No, the standard "mailto:" protocol used by QR codes does not support attachments for security and technical reasons. You can, however, include a link to a file in the message body.',
      },
    ],
  },
  {
    id: 'phone',
    name: 'Phone QR Code',
    path: '/phone',
    description: 'Generate a QR code that opens the dialer with your number.',
    longDescription: 'Create a QR code that opens the dialer app on any smartphone with your number ready to call. Perfect for support lines and business flyers.',
    icon: <PhoneIcon className="w-8 h-8" />,
    color: 'bg-sky-50 text-sky-600',
    metaTitle: 'Phone Number QR Code Generator | QR Studio',
    metaDescription: 'Create a phone QR code that dials a number automatically when scanned. Fast way to share business contact lines.',
    faqItems: [
      {
        question: 'How do I create a phone QR code?',
        answer: 'Enter your phone number, including the country code for international compatibility. Click "Generate" and download your QR code. When scanned, it will open the phone\'s dialer app with your number already filled in.',
      },
      {
        question: 'Will the phone call be made automatically?',
        answer: 'No. For security reasons, scanning the code will open the dialer app with the number ready, but the user must still press the "Call" button to initiate the call.',
      },
      {
        question: 'Does this work for international numbers?',
        answer: 'Yes. We recommend using the full international format (e.g., +1 for USA, +44 for UK) to ensure the number can be dialed correctly from any country in the world.',
      },
      {
        question: 'Can I use this for WhatsApp?',
        answer: 'While this tool is for direct phone calls, you can use our URL QR code generator with a WhatsApp "wa.me" link to create a QR code that opens a WhatsApp chat directly.',
      },
    ],
  },
];
