
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service | QR Studio',
  description: 'The terms and conditions for using QR Studio\'s free online QR code generation tools.',
  alternates: {
    canonical: '/terms-of-service',
  },
  robots: {
    index: true,
    follow: true,
  },
};

export default function TermsOfService() {
  return (
    <div className="container mx-auto px-4 py-16 max-w-4xl">
      <h1 className="text-4xl font-extrabold text-text-primary mb-8">Terms of Service</h1>
      
      <div className="prose prose-indigo max-w-none space-y-8 text-text-secondary leading-relaxed">
        <p className="text-sm italic">Last Updated: December 29, 2025</p>

        <section>
          <h2 className="text-2xl font-bold text-text-primary mb-4">1. Agreement to Terms</h2>
          <p>
            By accessing or using <strong>QR Studio</strong> (qr-generator.cc), you agree to comply with and be bound by these Terms of Service. If you do not agree to these terms, please do not use our service. Our tools are provided as-is for the benefit of our users.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-text-primary mb-4">2. Description of Service</h2>
          <p>
            QR Studio is an online tool service providing various QR code generation utilities. Our service allows users to generate static QR codes for personal and commercial use without the need for registration or server-side data processing.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-text-primary mb-4">3. User Conduct and License</h2>
          <p>
            We grant you a non-exclusive, non-transferable, revocable license to use our QR code generators. You agree to use the service only for lawful purposes. While our tools are free for both personal and commercial projects, you may not:
          </p>
          <ul className="list-disc pl-5 mt-4 space-y-2">
            <li>Use the service to generate QR codes containing illegal, harmful, or malicious content.</li>
            <li>Attempt to reverse engineer or disrupt the technical infrastructure of the site.</li>
            <li>Automate the use of the site via scripts or bots without prior written consent.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-text-primary mb-4">4. Intellectual Property</h2>
          <p>
            The content on this website, including text, graphics, logos, and software, is the property of QR Studio or its content suppliers and protected by international copyright laws. The resulting QR code images generated by you are your property to use as you see fit.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-text-primary mb-4">5. Disclaimer of Warranties</h2>
          <p>
            The service is provided on an &quot;as is&quot; and &quot;as available&quot; basis. QR Studio makes no warranties, express or implied, regarding the reliability or availability of the service. We do not guarantee that the QR codes generated will be compatible with all scanning hardware or software, although we follow standard protocols.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-text-primary mb-4">6. Limitation of Liability</h2>
          <p>
            In no event shall QR Studio, its creators, or its affiliates be liable for any indirect, incidental, special, or consequential damages arising out of the use or inability to use the service, even if advised of the possibility of such damages.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-text-primary mb-4">7. Changes to Terms</h2>
          <p>
            We reserve the right to modify these Terms of Service at any time. Your continued use of the site following any changes signifies your acceptance of the new terms.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-bold text-text-primary mb-4">8. Contact</h2>
          <p>
            Questions about the Terms of Service should be sent to us at <a href="mailto:contact@qr-generator.cc" className="text-primary hover:underline">contact@qr-generator.cc</a>.
          </p>
        </section>
      </div>
    </div>
  );
}
